"""add_company_user_group

Revision ID: 25606bb8e81c
Revises: 886d3496e46e
Create Date: 2026-03-25 12:15:37.258981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '25606bb8e81c'
down_revision: Union[str, None] = '886d3496e46e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add nullable first, backfill, then set NOT NULL
    op.add_column('company_users', sa.Column('user_group', sa.String(length=50), nullable=True))
    op.execute("UPDATE company_users SET user_group = 'Users' WHERE user_group IS NULL")
    op.alter_column('company_users', 'user_group', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_users', 'user_group')
    # ### end Alembic commands ###
