"""cart_item_company_id

Revision ID: 473e7e0a8dd3
Revises: 002
Create Date: 2026-03-16 08:17:35.145019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '473e7e0a8dd3'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('abandoned_carts', 'items_snapshot',
               existing_type=sa.TEXT(),
               comment='JSON snapshot of cart items',
               existing_nullable=False)
    op.create_index(op.f('ix_abandoned_carts_id'), 'abandoned_carts', ['id'], unique=False)
    op.alter_column('audit_log', 'old_values',
               existing_type=sa.TEXT(),
               comment='JSON of old field values',
               existing_nullable=True)
    op.alter_column('audit_log', 'new_values',
               existing_type=sa.TEXT(),
               comment='JSON of new field values',
               existing_nullable=True)
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.add_column('cart_items', sa.Column('company_id', sa.UUID(), nullable=False))
    op.add_column('cart_items', sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Tier price at time item was added'))
    op.drop_index(op.f('ix_cart_items_user_id'), table_name='cart_items')
    op.create_index(op.f('ix_cart_items_company_id'), 'cart_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    op.drop_constraint(op.f('cart_items_user_id_fkey'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cart_items', 'price_at_add')
    op.drop_column('cart_items', 'user_id')
    op.drop_constraint(op.f('categories_slug_key'), 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.alter_column('companies', 'shipping_override_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Fixed shipping cost override. NULL = use tier brackets.',
               existing_nullable=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_company_users_id'), 'company_users', ['id'], unique=False)
    op.alter_column('contacts', 'notify_order_confirmation',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('contacts', 'notify_order_shipped',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('contacts', 'notify_invoices',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.alter_column('email_templates', 'body_html',
               existing_type=sa.TEXT(),
               comment='Jinja2 HTML template',
               existing_nullable=False)
    op.alter_column('email_templates', 'body_text',
               existing_type=sa.TEXT(),
               comment='Plain text fallback',
               existing_nullable=True)
    op.alter_column('email_templates', 'available_variables',
               existing_type=sa.TEXT(),
               comment='JSON array of variable names',
               existing_nullable=True)
    op.drop_constraint(op.f('email_templates_trigger_event_key'), 'email_templates', type_='unique')
    op.drop_index(op.f('ix_email_templates_trigger_event'), table_name='email_templates')
    op.create_index(op.f('ix_email_templates_trigger_event'), 'email_templates', ['trigger_event'], unique=True)
    op.create_index(op.f('ix_email_templates_id'), 'email_templates', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_adjustments_id'), 'inventory_adjustments', ['id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Price snapshotted at time of order',
               existing_nullable=False)
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.alter_column('order_templates', 'items',
               existing_type=sa.TEXT(),
               comment='JSON array of {sku, quantity}',
               existing_nullable=False)
    op.create_index(op.f('ix_order_templates_id'), 'order_templates', ['id'], unique=False)
    op.alter_column('orders', 'shipping_address_snapshot',
               existing_type=sa.TEXT(),
               comment='JSON snapshot of address at time of order',
               existing_nullable=True)
    op.drop_constraint(op.f('orders_order_number_key'), 'orders', type_='unique')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_price_list_requests_id'), 'price_list_requests', ['id'], unique=False)
    op.alter_column('pricing_tiers', 'discount_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Discount percentage off retail price (e.g. 25.00 = 25%)',
               existing_nullable=False)
    op.create_index(op.f('ix_pricing_tiers_id'), 'pricing_tiers', ['id'], unique=False)
    op.create_index(op.f('ix_product_assets_id'), 'product_assets', ['id'], unique=False)
    op.create_index(op.f('ix_product_categories_id'), 'product_categories', ['id'], unique=False)
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    op.drop_constraint(op.f('product_variants_sku_key'), 'product_variants', type_='unique')
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=True)
    op.create_index(op.f('ix_product_variants_id'), 'product_variants', ['id'], unique=False)
    op.alter_column('products', 'moq',
               existing_type=sa.INTEGER(),
               comment='Minimum order quantity',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_products_search_vector'), table_name='products', postgresql_using='gin')
    op.drop_constraint(op.f('products_slug_key'), 'products', type_='unique')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_qb_sync_log_id'), 'qb_sync_log', ['id'], unique=False)
    op.create_index(op.f('ix_rma_items_id'), 'rma_items', ['id'], unique=False)
    op.drop_constraint(op.f('rma_requests_rma_number_key'), 'rma_requests', type_='unique')
    op.drop_index(op.f('ix_rma_requests_rma_number'), table_name='rma_requests')
    op.create_index(op.f('ix_rma_requests_rma_number'), 'rma_requests', ['rma_number'], unique=True)
    op.create_index(op.f('ix_rma_requests_id'), 'rma_requests', ['id'], unique=False)
    op.drop_constraint(op.f('settings_key_key'), 'settings', type_='unique')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.alter_column('shipping_brackets', 'max_units',
               existing_type=sa.INTEGER(),
               comment='NULL = no upper bound',
               existing_nullable=True)
    op.create_index(op.f('ix_shipping_brackets_id'), 'shipping_brackets', ['id'], unique=False)
    op.create_index(op.f('ix_shipping_tiers_id'), 'shipping_tiers', ['id'], unique=False)
    op.create_index(op.f('ix_user_addresses_id'), 'user_addresses', ['id'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_constraint(op.f('warehouses_code_key'), 'warehouses', type_='unique')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=True)
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.alter_column('webhook_log', 'event_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Provider event ID (e.g. Stripe evt_xxx) for deduplication',
               existing_nullable=False)
    op.alter_column('webhook_log', 'payload',
               existing_type=sa.TEXT(),
               comment='Raw JSON payload',
               existing_nullable=False)
    op.drop_constraint(op.f('webhook_log_event_id_key'), 'webhook_log', type_='unique')
    op.drop_index(op.f('ix_webhook_log_event_id'), table_name='webhook_log')
    op.create_index(op.f('ix_webhook_log_event_id'), 'webhook_log', ['event_id'], unique=True)
    op.create_index(op.f('ix_webhook_log_id'), 'webhook_log', ['id'], unique=False)
    op.create_index(op.f('ix_wholesale_applications_id'), 'wholesale_applications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wholesale_applications_id'), table_name='wholesale_applications')
    op.drop_index(op.f('ix_webhook_log_id'), table_name='webhook_log')
    op.drop_index(op.f('ix_webhook_log_event_id'), table_name='webhook_log')
    op.create_index(op.f('ix_webhook_log_event_id'), 'webhook_log', ['event_id'], unique=False)
    op.create_unique_constraint(op.f('webhook_log_event_id_key'), 'webhook_log', ['event_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('webhook_log', 'payload',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Raw JSON payload',
               existing_nullable=False)
    op.alter_column('webhook_log', 'event_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Provider event ID (e.g. Stripe evt_xxx) for deduplication',
               existing_nullable=False)
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=False)
    op.create_unique_constraint(op.f('warehouses_code_key'), 'warehouses', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_user_addresses_id'), table_name='user_addresses')
    op.drop_index(op.f('ix_shipping_tiers_id'), table_name='shipping_tiers')
    op.drop_index(op.f('ix_shipping_brackets_id'), table_name='shipping_brackets')
    op.alter_column('shipping_brackets', 'max_units',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='NULL = no upper bound',
               existing_nullable=True)
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=False)
    op.create_unique_constraint(op.f('settings_key_key'), 'settings', ['key'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_rma_requests_id'), table_name='rma_requests')
    op.drop_index(op.f('ix_rma_requests_rma_number'), table_name='rma_requests')
    op.create_index(op.f('ix_rma_requests_rma_number'), 'rma_requests', ['rma_number'], unique=False)
    op.create_unique_constraint(op.f('rma_requests_rma_number_key'), 'rma_requests', ['rma_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_rma_items_id'), table_name='rma_items')
    op.drop_index(op.f('ix_qb_sync_log_id'), table_name='qb_sync_log')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=False)
    op.create_unique_constraint(op.f('products_slug_key'), 'products', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_products_search_vector'), 'products', ['search_vector'], unique=False, postgresql_using='gin')
    op.alter_column('products', 'moq',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Minimum order quantity',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_product_variants_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=False)
    op.create_unique_constraint(op.f('product_variants_sku_key'), 'product_variants', ['sku'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.drop_index(op.f('ix_product_categories_id'), table_name='product_categories')
    op.drop_index(op.f('ix_product_assets_id'), table_name='product_assets')
    op.drop_index(op.f('ix_pricing_tiers_id'), table_name='pricing_tiers')
    op.alter_column('pricing_tiers', 'discount_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Discount percentage off retail price (e.g. 25.00 = 25%)',
               existing_nullable=False)
    op.drop_index(op.f('ix_price_list_requests_id'), table_name='price_list_requests')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=False)
    op.create_unique_constraint(op.f('orders_order_number_key'), 'orders', ['order_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('orders', 'shipping_address_snapshot',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON snapshot of address at time of order',
               existing_nullable=True)
    op.drop_index(op.f('ix_order_templates_id'), table_name='order_templates')
    op.alter_column('order_templates', 'items',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON array of {sku, quantity}',
               existing_nullable=False)
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Price snapshotted at time of order',
               existing_nullable=False)
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_inventory_adjustments_id'), table_name='inventory_adjustments')
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.drop_index(op.f('ix_email_templates_id'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_trigger_event'), table_name='email_templates')
    op.create_index(op.f('ix_email_templates_trigger_event'), 'email_templates', ['trigger_event'], unique=False)
    op.create_unique_constraint(op.f('email_templates_trigger_event_key'), 'email_templates', ['trigger_event'], postgresql_nulls_not_distinct=False)
    op.alter_column('email_templates', 'available_variables',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON array of variable names',
               existing_nullable=True)
    op.alter_column('email_templates', 'body_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Plain text fallback',
               existing_nullable=True)
    op.alter_column('email_templates', 'body_html',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Jinja2 HTML template',
               existing_nullable=False)
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.alter_column('contacts', 'notify_invoices',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('contacts', 'notify_order_shipped',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('contacts', 'notify_order_confirmation',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_company_users_id'), table_name='company_users')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.alter_column('companies', 'shipping_override_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Fixed shipping cost override. NULL = use tier brackets.',
               existing_nullable=True)
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=False)
    op.create_unique_constraint(op.f('categories_slug_key'), 'categories', ['slug'], postgresql_nulls_not_distinct=False)
    op.add_column('cart_items', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('cart_items', sa.Column('price_at_add', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(op.f('cart_items_user_id_fkey'), 'cart_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_company_id'), table_name='cart_items')
    op.create_index(op.f('ix_cart_items_user_id'), 'cart_items', ['user_id'], unique=False)
    op.drop_column('cart_items', 'unit_price')
    op.drop_column('cart_items', 'company_id')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.alter_column('audit_log', 'new_values',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON of new field values',
               existing_nullable=True)
    op.alter_column('audit_log', 'old_values',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON of old field values',
               existing_nullable=True)
    op.drop_index(op.f('ix_abandoned_carts_id'), table_name='abandoned_carts')
    op.alter_column('abandoned_carts', 'items_snapshot',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON snapshot of cart items',
               existing_nullable=False)
    # ### end Alembic commands ###
