"""add_default_payment_method

Revision ID: 55fb5336e213
Revises: 25606bb8e81c
Create Date: 2026-03-25 14:31:26.728259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '55fb5336e213'
down_revision: Union[str, None] = '25606bb8e81c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('default_payment_method_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'default_payment_method_id')
    # ### end Alembic commands ###
