"""add_contact_full_fields

Revision ID: 886d3496e46e
Revises: e5d6991298ab
Create Date: 2026-03-25 11:43:54.705761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '886d3496e46e'
down_revision: Union[str, None] = 'e5d6991298ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('department', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('time_zone', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('phone_ext', sa.String(length=20), nullable=True))
    op.add_column('contacts', sa.Column('fax', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('web_address', sa.String(length=500), nullable=True))
    op.add_column('contacts', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('contacts', sa.Column('home_address1', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('home_address2', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('home_postal_code', sa.String(length=20), nullable=True))
    op.add_column('contacts', sa.Column('home_city', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('home_state', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('home_country', sa.String(length=2), nullable=True))
    op.add_column('contacts', sa.Column('home_phone', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('home_fax', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('home_email', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('alt_contacts', sa.Text(), nullable=True))
    op.drop_column('contacts', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('contacts', 'alt_contacts')
    op.drop_column('contacts', 'home_email')
    op.drop_column('contacts', 'home_fax')
    op.drop_column('contacts', 'home_phone')
    op.drop_column('contacts', 'home_country')
    op.drop_column('contacts', 'home_state')
    op.drop_column('contacts', 'home_city')
    op.drop_column('contacts', 'home_postal_code')
    op.drop_column('contacts', 'home_address2')
    op.drop_column('contacts', 'home_address1')
    op.drop_column('contacts', 'notes')
    op.drop_column('contacts', 'web_address')
    op.drop_column('contacts', 'fax')
    op.drop_column('contacts', 'phone_ext')
    op.drop_column('contacts', 'time_zone')
    op.drop_column('contacts', 'department')
    # ### end Alembic commands ###
