"""add_company_profile_fields

Revision ID: 90b0e29cf676
Revises: f3a9c1d2e456
Create Date: 2026-03-25 09:31:27.881869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '90b0e29cf676'
down_revision: Union[str, None] = 'f3a9c1d2e456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('fax', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('tax_id_expiry', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('secondary_business', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('estimated_annual_volume', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('ppac_number', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('ppai_number', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('asi_number', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'asi_number')
    op.drop_column('companies', 'ppai_number')
    op.drop_column('companies', 'ppac_number')
    op.drop_column('companies', 'estimated_annual_volume')
    op.drop_column('companies', 'secondary_business')
    op.drop_column('companies', 'tax_id_expiry')
    op.drop_column('companies', 'fax')
    # ### end Alembic commands ###
