"""company_stripe_customer_id

Revision ID: e114fbbfad6b
Revises: 473e7e0a8dd3
Create Date: 2026-03-16 09:19:07.012428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e114fbbfad6b'
down_revision: Union[str, None] = '473e7e0a8dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'stripe_customer_id')
    # ### end Alembic commands ###
