"""add_address_full_name_phone

Revision ID: e5d6991298ab
Revises: 90b0e29cf676
Create Date: 2026-03-25 11:09:04.014339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e5d6991298ab'
down_revision: Union[str, None] = '90b0e29cf676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_addresses', sa.Column('full_name', sa.String(length=200), nullable=True))
    op.add_column('user_addresses', sa.Column('phone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_addresses', 'phone')
    op.drop_column('user_addresses', 'full_name')
    # ### end Alembic commands ###
